### ISSUE TITLE
Issues in type hints in the circles class

### ISSUE THREAD

**Issue by Joshuah143** [what3words/w3w-python-wrapper#13]
This code ([line 343 in what3words.py](https://github.com/what3words/w3w-python-wrapper/blob/a8243eac4b8e98d56c490e32d542bcd5e6bb9401/what3words/what3words.py#L343) ):

    """
        Constructor
        Params
        ------
        :param sw: the coordinates of the southwest corner
        :param ne: the coordinates of the northeast corner
    """

includes params for sw and ne, despite the fact that those don't exist at all. This makes the code hard to read and understand. It is also unclear as to if you could use an instance of the Coordinates class to fille the first positional argument.

Maybe rewrite this little piece for clearity.

**Comment by ManuCiao** [comment]
this will be updated with the new upcoming release @Joshuah143
