### ISSUE TITLE
Does my app always need to be online?

### ISSUE THREAD

**Issue by hickford** [what3words/w3w-python-wrapper#4]
Silly question, but I couldn't find it in the [FAQ](http://what3words.com/faq/). Would my app always need to connect to the internet to resolve addresses? The FAQ mentions an offline mode.

**Comment by thiswilliam** [comment]
Hi Mirth,

To resolve a 3 word address offline requires the integration of our SDK (~10mb). This allows all 57 trillion 3 word combinations (across 9 languages and counting) to be resolved to a lat,long offline.

We require the signing of a simple licence agreement to get the SDK. If this is of interest let me know and I will get the partnerships team to reach out.

Hope you enjoy using what3words and let me know if you have any other queries.

Best,
Will

**Comment by hickford** [comment]
Hi Will, thanks for your reply.
